from .settings import (
    TFLITE_MODEL_PATH,
    LABELS_PATH,
    MODEL_INPUT_SIZE,
    UPLOAD_DIR,
    SAVED_IMAGES_DIR,
    MAX_FILE_SIZE,
    ALLOWED_EXTENSIONS,
    API_TITLE,
    API_VERSION,
    API_DESCRIPTION,
    CORS_ORIGINS,
)

__all__ = [
    "TFLITE_MODEL_PATH",
    "LABELS_PATH",
    "MODEL_INPUT_SIZE",
    "UPLOAD_DIR",
    "SAVED_IMAGES_DIR",
    "MAX_FILE_SIZE",
    "ALLOWED_EXTENSIONS",
    "API_TITLE",
    "API_VERSION",
    "API_DESCRIPTION",
    "CORS_ORIGINS",
]
